project:
  type: book
  output-dir: docs

book:
  title: "Probability Theory"
  author: "Wu Yanzu"
  date: "2023/12/2"
  search: true
  repo-url: https://github.com/Zeuyel/Probability_Book_Hong
  repo-actions: [edit]
  chapters:
    - index.qmd
    - intro.qmd
    - Foundation of Probability Theory.md
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

comments: 
  hypothesis: true